### ISSUE TITLE
Navbar appears but doesn't disappears

### ISSUE THREAD

**Issue by aciceri** [hemangsk/DevJournal#2]
When I click on the "three-row button" in upper right the menu correctly appears but when I click it again it doesn't disappear.

I refer to this menu:
![image](https://cloud.githubusercontent.com/assets/2318843/16835357/a7605a7c-49b8-11e6-858c-1c9736e6ca3c.png)

Good template anyway ;)

**Comment by hemangsk** [comment]
@andrea96 I've fixed the code and code is merged into master.  :smile:  
9dc1cc9b12b2e766a92fdf44055ca04543893abb
