### ISSUE TITLE
Background color theme disappears 

### ISSUE THREAD

**Issue by wrillrysata** [hemangsk/DevJournal#8]
Hi, great theme! 
 After forking, the geeky background color disappears. Why is that? 
Ref : https://ijebusoma.github.io/blog-site/

**Comment by hemangsk** [comment]
Hey @Ijebusoma , Updating the baseurl at https://github.com/Ijebusoma/blog-site/blob/master/_config.yml#L17 should fix the issue. Its not able to find the correct css at /css/style.css which should be /blog-site/css/style.css. So adding ```blog-site``` (your repository's name) in baseurl should do the job.  
I'm glad you liked it. Do let me know if this doesn't fix it.

**Comment by hemangsk** [comment]
Please reopen incase this issue persists.
